title: Desarrollos Multiplataforma y Algo Mas
email: mrduarte55@gmail.com
description:  "'El valor de la innovación no está en evitar que te copien, sino en conseguir que todos te quieran copiar' Enrique Dans.                Bienvenidos al blog de Desarrollo multiplataforma más consultado de toda  habla hispana, esperamos que tu estadía en este site sea de gran ayuda para tu desarrollo."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://JonathanDuarte.github.io" # the base hostname & protocol for your site
github_username:  jonathanduarte

# Build settings
markdown: kramdown
