title: Desarrollos Multiplataforma y Algo Mas
email: mrduarte55@gmail.com
description: "Bienvenidos al blog de Desarrollo multiplataforma más consultado de toda  habla hispana, esperamos que tu estadía en este site sea de gran ayuda para tu desarrollo.</br>
<i><b>'El valor de la innovación no está en evitar que te copien, sino en conseguir que todos te quieran copiar' Enrique Dans.</i></b>"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://JonathanDuarte.github.io" # the base hostname & protocol for your site
github_username:  jonathanduarte
twitter_username: jodayc055

# Build settings
markdown: kramdown
